### ISSUE TITLE
TypeError: (0 , _react2.getRouteName) is not a function

### ISSUE THREAD

**Issue by sommesh** [eliot-akira/mna#1]
Hi @eliot-akira 

We are trying to explore mna, so we took template-basic folder as example project .First of all we using npm so followed as below
1 . To install dependencies , **npm i** 
2. To run, **npm run dev**
3.Go to browser in 3000 port ,
 we got issue in rendering as TypeError: (0 , _react2.getRouteName) is not a function
**Browser Screenshot:**
![image](https://user-images.githubusercontent.com/11015348/78747999-7bef1280-7988-11ea-9098-6cfa53e84be8.png)
**Terminal screenshot:**
![image](https://user-images.githubusercontent.com/11015348/78748065-a4770c80-7988-11ea-95ea-8bfb26172b8c.png)

Kindly provide us any solution for this issues.

**Comment by eliot-akira** [comment]
Hello, thank you for the issue description.

As a test, I cloned this repo and ran the same commands in the `template-basic` folder:

```
npm i && npm run dev
```

It's working on my side.

![mna-template-basic-run-dev](https://user-images.githubusercontent.com/5352434/78822342-3576d380-79db-11ea-8f8b-ad3f03b12a6b.png)

Just in case, I pushed some small local changes I had (in unrelated folders) and published new versions of `@mna` modules. Could you run the following to reinstall them?

```
rm package-lock.json && rm -rf node_modules && npm i
```

Please see if `npm run dev` works after that.

---
I noticed in your screenshot that you're running Windows. That shouldn't make a difference, but so far I've only tested on macOS and Linux. Maybe you could see if it works on [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by eliot-akira** [comment]
Actually, I do see the issue now.

Looks like it's related to the builder, how the `@mna` modules are built and published. It's a Babel transpilation issue with default and named exports. OK, I'll investigate further and try to solve this.

**Comment by eliot-akira** [comment]
So, I couldn't find exactly which dependency or version broke backward compatibility, but it's related to mixing export default and named exports.  I managed to work around the issue, and published newly built modules.

Please try reinstalling everything with:

```
rm package-lock.json && rm -rf node_modules && npm i
```

Then, you can run the following to confirm that it's at version `2.3.0`.

```
cat node_modules/@mna/react-server/package.json
```

**Comment by sommesh** [comment]
Yeah, Awsome now it's working fine. Thanks for the needful from your end @eliot-akira

**Comment by eliot-akira** [comment]
Just to follow through, I did find the exact line that caused the issue - it was adding an `export default` to a module that had named exports only before. Removing the line solved it cleanly, and I republished the module.

**Comment by sommesh** [comment]
I have pulled latest commit.
I got issues while running

**Terminal Screenshot :**

![image](https://user-images.githubusercontent.com/11015348/79116604-90774480-7da6-11ea-9c8e-ea234eddce12.png)

Kindly provide us any solution for this issues.

**Comment by eliot-akira** [comment]
Hi @sommesh - thanks, from the screenshot I see that somehow the package was published in an unbuilt state. OK, I'm rebuilt and published a new version.

Could you try reinstalling again? I'm not sure if it's necessary to remove lock file and node_modules folder - it might work just to run `npm update`.

**Comment by sommesh** [comment]
Yeah, Awesome now it's working fine. Thanks for the needful from your end @eliot-akira
