### ISSUE TITLE
@mna/react-server breakage with express module

### ISSUE THREAD

**Issue by vamshi088** [eliot-akira/mna#11]
Hi @eliot-akira,
we got a situation while creating the react-server using createServer function.
Below is the issue 
**Server error TypeError: argument #2 unsupported type undefined at createError (webpack:///./node_modules/http-errors/index.js?:68:13) at SendStream.error (webpack:///./node_modules/@mna/server/static/send/index.js?:270:31) at SendStream.redirect (webpack:///./node_modules/@mna/server/static/middleware.js?:192:12) at SendStream.emit (events.js:311:20) at SendStream.redirect (webpack:///./node_modules/@mna/server/static/send/index.js?:479:10) at onstat (webpack:///./node_modules/@mna/server/static/send/index.js?:727:41) at FSReqCallback.oncomplete (fs.js:167:5)**

When checked, found it got break with express module with version 4.18.1
working fine till the express version of 4.17.1
As express module coming as inner dependency of webpack, can't restrict it update to latest version.
Since we are following your MNA format for our whole site, can you please suggest or provide some solution for this issue.

**Comment by eliot-akira** [comment]
Hi @vamshi088 - I'm no longer actively developing this library, so if you would like to create a pull request to fix the issue, I can take a look and merge it. For the long-term, I believe it's best if you fork the library and continue developing it on your own.

From the debug trace, it looks like the error is happening at `@mna/server/static/send/index.js:270:31`.


```js
SendStream.prototype.error = function error (status, err) {
  // emit if listeners instead of responding
  if (hasListeners(this, 'error')) {
    return this.emit('error', createError(status, err, {
      expose: false
    }))
  }
  ...
}
```

The error message is saying `err` is undefined, so perhaps it expects `null` instead. Proposed solution:

```js
SendStream.prototype.error = function error (status, err = null) {
  ...
}
```

**Comment by vamshi088** [comment]
HI @eliot-akira, Thanks for your support and valuable information. the proposed solution working wonderfully..
As per your above comments, forked the library and committed the changes.
Raised the PR https://github.com/eliot-akira/mna/pull/12#issue-1318261122

Please have a look and merge the code. 
Thank you.

**Comment by vamshi088** [comment]
@eliot-akira , I tried installing the package by clearing the node modules and yarn.lock and package-lock.josn.
after installation I still see the same old code other than the change which we did yesterday.
Can you confirm after merging do you need to publish the changes so that those changes can be reflected in npm.
![image](https://user-images.githubusercontent.com/110034803/181189629-4e4f28d6-4747-4d41-bf3a-abe5cafe445a.png)
I can see last publish was done 2 years back..
Can you please check once
