### ISSUE TITLE
@mna/server changes didn't got published

### ISSUE THREAD

**Issue by vamshi088** [eliot-akira/mna#13]
Hi @eliot-akira,
https://github.com/eliot-akira/mna/pull/12#issue-1318261122 changes were not got published. 
https://github.com/eliot-akira/mna/issues/11#issuecomment-1196372120
can you please have a look and make the appropriate changes so that we can install with latest fix.

**Comment by eliot-akira** [comment]
Hi @vamshi088,

I published `@mna/server` version 2.3.6 with your pull request merged.

Starting from a fresh Git clone of this `mna` repository, I had difficulty with `npm install`. One of the dependencies `node-sass` is an old version that requires Python 2 for building itself. After installing it with `sudo apt install python2`, there was another mysterious error, which I finally was able to solve by upgrading `node-sass` to the next major version. After that I was able to rebuild all packages.

**Comment by vamshi088** [comment]
Thanks for the needful from your end @eliot-akira..
