### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by DineshLt93** [eliot-akira/mna#3]
Hi,

Just I have downloaded your git file and run the file it's working fine.

I can't able to get the current location for this command window.location.path.
I am getting the issue **window is not defined.**
I can't able to use the below keywords also.

window.location.orgin
window.location.match
window.location.hostname

Kindly give any suggestions.

**Comment by eliot-akira** [comment]
This is because projects using @mna/builder are full-stack React apps, which are rendered on server-side as well as client/browser.

That means the app must be able to fully render on the server, without depending on the browser environment. Code that accesses global `window` should only run on client-side, usually in (or after) the `componentDidMount` hook.

**Comment by DineshLt93** [comment]
Hi @eliot-akira 

Thanks for your information.

Just I have copied the @mna folder and paste inside the src folder
Then I have changed the path in the "@mna/" node module path into the "../" internal path.
But I have to face the below issue in @mna/react-ui/Layout/index.js file
**Issue: ReferenceError: exports is not defined**


![mna-issue](https://user-images.githubusercontent.com/62551762/80393422-17abd880-88ce-11ea-82ff-dce4ec5583e8.png)


Kindly provide us any solution to this problem.

**Comment by eliot-akira** [comment]
> Just I have copied the @mna folder and paste inside the src folder
> Then I have changed the path in the "@mna/" node module path into the "../" internal path.

This is probably because modules in `node_modules` are not transpiled. Please try the following to set it up correctly:

```sh
cd src
rm -rf @mna
git clone https://github.com/eliot-akira/mna @mna
```

And remove the symbolic link:

```sh
rm node_modules/@mna
```

**Comment by DineshLt93** [comment]
> This is because projects using @mna/builder are full-stack React apps, which are rendered on server-side as well as client/browser.
> 
> That means the app must be able to fully render on the server, without depending on the browser environment. Code that accesses global `window` should only run on client-side, usually in (or after) the `componentDidMount` hook.

Hi @eliot-akira 
Thanks for the information.
Is there any other solution to fix that window issue using @mna/builder. 
Kindly let me know.

**Comment by eliot-akira** [comment]
Unfortunately, this is not an issue with @mna/builder, it's true for all full-stack React apps. Browser-side libraries that depend on global `window` must be loaded only on the client-side.

You may be able to load it in `src/client.js`, and use it in (or after) the componentDidMount hook.

Another possible solution is to load it conditionally:

```js
if (typeof window!=='undefined') {
  const lib = require('./client-side-library')
}
```

**Comment by DineshLt93** [comment]
Hi @eliot-akira 

Thanks for your information

**Comment by eliot-akira** [comment]
For reference, here's the same issue discussed: [How to properly deal with window undefined error in React server-side rendering](https://stackoverflow.com/questions/38412135/how-to-properly-deal-with-window-undefined-error-in-react-server-side-rendering).
