### ISSUE TITLE
set custom header and body

### ISSUE THREAD

**Issue by sommesh** [eliot-akira/mna#5]
Hi

I have used the below way to change the API endpoint's base URL as below:

```
import api from '@mna/api'

api.setDefaultOptions({
  baseURL: 'https://mypostapi'
})
```
using below api callback function:

```
_api2.default.post('/post', {
type: 'user',
action: 'login',
data
})
```

In '`@mna/api'` kindly let us know how shall we override the **header** to use our **custom headers** like below.
![customKey](https://user-images.githubusercontent.com/11015348/80985407-d034c780-8e4c-11ea-9beb-84f9eed667f4.png)

And how shall we send **rawBody** using MNA something like below.
![customBody](https://user-images.githubusercontent.com/11015348/80985384-c6ab5f80-8e4c-11ea-9b0f-c1de03456377.png)

**Comment by eliot-akira** [comment]
The [`@mna/api`](https://github.com/eliot-akira/mna/blob/92f8a684c3558c5bad76f5c66b912b25720aee82/api/API.ts) module is a minimal wrapper around a library called [`axios`](https://www.npmjs.com/package/axios). Here's the [documentation on request configuration](https://www.npmjs.com/package/axios#request-config).

For customized behavior, it might simpler to use `axios` directly.

**Comment by sommesh** [comment]
@eliot-akira  Okay, thanks for the information.
