### ISSUE TITLE
Deploy on Windows

### ISSUE THREAD

**Issue by sommesh** [eliot-akira/mna#6]
I'm trying to Deploy the site in windows that were built using MNA.
The first command was `npm install`,
The second command was `npm run build`.
These two commands ran successfully.
Please let me know, how to make it run using the **pm2** process manager on Windows.
It would be helpful if you provide us additional information on how to deploy from Windows.

**Note:** When running `npm start` its working fine in Linux based system but not on Windows.

**Comment by eliot-akira** [comment]
I don't have a local machine running Windows, so I'm afraid I won't be of much help.

For local development, you may have better luck running [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I've heard WSL 2 was released recently, which has near-perfect Linux integration.

For using PM2 as process manager, the key points are to:

- Set up a cron job to save and restore processes. Here's an example from a production server:

  ```
  # Restart processes on server reboot
  @reboot /home/ubuntu/n/bin/node /usr/bin/pm2 resurrect

  # Save process list
  */5 * * * * /home/ubuntu/n/bin/node /usr/bin/pm2 save > /dev/null
  ```

  The path to `node` would probably be different in your case, wherever it was installed.

- Start PM2 daemon on system start and reboot

  PM2 has a helper command that generates a startup script. Here's the documentation: https://pm2.keymetrics.io/docs/usage/startup/

  Looking at the list of supported systems, Windows is apparently not supported. However, I'd guess that it must be possible to manually set it up.

**Comment by sommesh** [comment]
@eliot-akira Thanks for your support and valuable information on the same.
