### ISSUE TITLE
Is MNA rendered in server side (SSR)

### ISSUE THREAD

**Issue by sommesh** [eliot-akira/mna#9]
As I'm new to server-side rendering, could you please confirm me if a site developed from your MNA is running as SSR?

**Comment by eliot-akira** [comment]
Yes, it is. Here's where it happens, in [mna/react-server/render](https://github.com/eliot-akira/mna/blob/92f8a684c3558c5bad76f5c66b912b25720aee82/react-server/render/index.js).
